test_that("provider settings status lines are readable and do not reveal secrets", {
  tmpDir = tempfile("wmfm-provider-stage22-6-")
  withr::local_options(list(wmfm.config_dir = tmpDir))
  withr::local_envvar(list(ANTHROPIC_API_KEY = "super-secret-value"), .local_envir = parent.frame())

  statusText = paste(buildProviderSettingsStatusLines(buildProviderSettingsState()), collapse = "\n")

  expect_match(statusText, "Provider credential/status summary:", fixed = TRUE)
  expect_match(statusText, "- Claude: available", fixed = TRUE)
  expect_match(statusText, "source: env:ANTHROPIC_API_KEY", fixed = TRUE)
  expect_false(grepl("super-secret-value", statusText, fixed = TRUE))
})

test_that("provider settings UI is consolidated to one heading", {
  html = as.character(appUI())

  expect_match(html, "Provider settings", fixed = TRUE)
  expect_no_match(html, "Chat provider", fixed = TRUE)
  expect_no_match(html, "Provider config (local, non-secret)", fixed = TRUE)
})

test_that("explanation provenance text includes provider and hh:mm:ss time", {
  txt = buildExplanationProvenanceText(
    providerLabel = "Ollama",
    modelName = "gpt-oss",
    generatedAt = as.POSIXct("2026-05-22 09:10:11", tz = "UTC")
  )

  expect_identical(txt, "Explanation generated by Ollama (gpt-oss) at 09:10:11")
})
