test_that("model plot observer registration is extracted from app server", {
  appServerText = readPackageText("R", "app-server.R")
  plotObserverText = readPackageText("R", "app-server-plot.R")

  expect_true(grepl("registerModelPlotObservers", appServerText, fixed = TRUE))
  expect_true(grepl("registerModelPlotObservers = function", plotObserverText, fixed = TRUE))
  expect_true(grepl("modelFit = modelFit", appServerText, fixed = TRUE))
  expect_true(grepl("output$plot_ci_controls_ui", plotObserverText, fixed = TRUE))
  expect_true(grepl("output$model_plot", plotObserverText, fixed = TRUE))
  expect_true(grepl("drawModelPlot", plotObserverText, fixed = TRUE))
  expect_true(grepl("output$modelPlotTypeUi", plotObserverText, fixed = TRUE))
  expect_true(grepl("output$modelPlotSmoothTrendUi", plotObserverText, fixed = TRUE))
  expect_true(grepl("output$modelPlotsPlot", plotObserverText, fixed = TRUE))
  expect_true(grepl("buildModelPlotTypeChoices", plotObserverText, fixed = TRUE))
  expect_true(grepl("Show smooth trend", plotObserverText, fixed = TRUE))
  expect_true(grepl("modelPlotShowSmoothTrend", plotObserverText, fixed = TRUE))
  expect_false(grepl("modelPlotSmoothSpan", plotObserverText, fixed = TRUE))
  expect_false(grepl("output$plot_ci_controls_ui = renderUI", appServerText, fixed = TRUE))
  expect_false(grepl("output$model_plot = renderPlot", appServerText, fixed = TRUE))
})
