testthat::test_that("README documents provider setup for new users", {
  readmeText = paste(readLines(findWmfmProjectFile("README.md"), warn = FALSE), collapse = "\n")

  testthat::expect_match(readmeText, "Configuring an AI provider", fixed = TRUE)
  testthat::expect_match(readmeText, "Provider setup", fixed = TRUE)
  testthat::expect_match(readmeText, "ANTHROPIC_API_KEY", fixed = TRUE)
  testthat::expect_match(readmeText, "OPENAI_API_KEY", fixed = TRUE)
  testthat::expect_match(readmeText, "usethis::edit_r_environ()", fixed = TRUE)
  testthat::expect_match(readmeText, "API credits", fixed = TRUE)
  testthat::expect_match(readmeText, "ChatGPT Plus subscription", fixed = TRUE)
  testthat::expect_match(readmeText, "Local Ollama", fixed = TRUE)
  testthat::expect_match(readmeText, "WMFM never displays API key values", fixed = TRUE)
  testthat::expect_match(readmeText, "Deployed Shiny apps", fixed = TRUE)
  testthat::expect_match(readmeText, "administrator-managed", fixed = TRUE)
  testthat::expect_false(grepl("Stage 20.16", readmeText, fixed = TRUE))
  testthat::expect_false(grepl("WMFM_SHOW_DEVELOPER_MODE", readmeText, fixed = TRUE))
})
