test_that("data loading observer registration is extracted from app server", {
  appServerText = readPackageText("R", "app-server.R")
  dataObserverText = readPackageText("R", "app-server-data-observers.R")

  expect_true(grepl("registerDataLoadObservers", appServerText, fixed = TRUE))
  expect_true(grepl("registerDataLoadObservers = function", dataObserverText, fixed = TRUE))
  expect_true(grepl("exampleLoadStatus = exampleLoadStatus", appServerText, fixed = TRUE))
  expect_true(grepl("resetModelPage = resetModelPage", appServerText, fixed = TRUE))
  expect_true(grepl("applyLoadedExampleToInputs = applyLoadedExampleToInputs", appServerText, fixed = TRUE))
  expect_true(grepl("observeEvent(input$file", dataObserverText, fixed = TRUE))
  expect_true(grepl("observeEvent(input$confirm_sep", dataObserverText, fixed = TRUE))
  expect_true(grepl("observeEvent(input$package_dataset", dataObserverText, fixed = TRUE))
  expect_true(grepl("observeEvent(input$loadExampleBtn", dataObserverText, fixed = TRUE))
  expect_false(grepl("loadDelimited = function", appServerText, fixed = TRUE))
  expect_false(grepl("observeEvent(input$file", appServerText, fixed = TRUE))
  expect_false(grepl("observeEvent(input$package_dataset", appServerText, fixed = TRUE))
})
