#' Application user interface
#'
#' Constructs the Shiny user interface for the Model Builder app.
#'
#' The interface allows the user to upload a data set, assign variables
#' to roles via drag-and-drop buckets, specify a model, view fitted-model
#' equations generated by a language model, and visualise the fitted model
#' against the observed data.
#'
#' @return A Shiny UI definition created with \code{fluidPage()}.
#'
#' @keywords internal
#'
#' @importFrom shiny fluidPage withMathJax titlePanel
#' @importFrom shiny tags HTML fluidRow column fileInput hr
#' @importFrom shiny h4 uiOutput tabsetPanel tabPanel
#' @importFrom shiny radioButtons textInput verbatimTextOutput
#' @importFrom shiny br actionButton plotOutput helpText
appUI = function() {
  fluidPage(
    withMathJax(),
    titlePanel("Model Builder"),

    tags$style(HTML("
      .bucket-list .rank-list {
        max-height: 8em;
        overflow-y: auto;
      }
    ")),

    # File selector
    fluidRow(
      column(
        12,
        fileInput(
          "file",
          "Choose CSV, TXT, or RDA",
          accept = c(".csv", ".txt", ".rda", ".RData")
        )
      )
    ),

    hr(),

    # Buckets
    h4("Assign variables"),
    uiOutput("var_buckets"),

    hr(),

    # Tabs
    tabsetPanel(
      id = "main_tabs",

      # ---- Tab 1: Model specification ----
      tabPanel(
        "Model",
        h4("Model type"),
        radioButtons(
          "model_type",
          label = NULL,
          choices = c(
            "Linear regression" = "lm",
            "Logistic regression (binomial, logit)" = "logistic",
            "Poisson regression (log link)" = "poisson"
          ),
          selected = "lm"
        ),

        h4("Response"),
        uiOutput("response_picker"),

        h4("Model formula"),
        textInput("formula_text", label = NULL, value = "", width = "100%"),
        verbatimTextOutput("formula_status"),

        br(),
        actionButton("fit_btn", "Fit model"),
        actionButton("reset_btn", "Reset model")
      ),

      # ---- Tab 2: Fitted model outputs ----
      tabPanel(
        "Fitted Model",
        h4("Model equation"),
        uiOutput("model_formula"),

        hr(),

        h4("Fitted equations"),
        uiOutput("model_equations"),

        hr(),

        h4("Regression table"),
        verbatimTextOutput("model_output"),

        hr(),

        h4("Model explanation"),
        uiOutput("model_explanation")
      ),

      # ---- Tab 3: Plot ----
      tabPanel(
        "Plot",
        h4("Data and fitted model"),
        plotOutput("model_plot"),
        helpText(
          "The plot shows the observed data and the fitted model ",
          "against one numeric predictor (x-axis), optionally separated by a factor."
        )
      )
    )
  )
}
