#' Map explanation zoom selection to CSS font size
#'
#' @param zoomLevel Character scalar zoom level from the UI control.
#'
#' @return A character scalar containing a CSS font-size value.
#' @keywords internal
mapExplanationZoomToFontSize = function(zoomLevel) {
  if (!is.character(zoomLevel) || length(zoomLevel) != 1 || is.na(zoomLevel)) {
    return("1rem")
  }

  zoomMap = c(
    small = "0.95rem",
    normal = "1.08rem",
    large = "1.28rem",
    presentation = "1.6rem"
  )

  if (!(zoomLevel %in% names(zoomMap))) {
    return("1rem")
  }

  unname(zoomMap[[zoomLevel]])
}

#' Render explanation text as safe paragraph HTML
#'
#' @param text Character scalar explanation text.
#' @param zoomLevel Character scalar zoom level from the UI control.
#'
#' @return A shiny tag object containing safe paragraph HTML.
#' @keywords internal
#' @importFrom htmltools htmlEscape
#' @importFrom shiny HTML tags
renderSafeExplanationHtml = function(text, zoomLevel = "normal") {
  if (is.null(text) || !is.character(text) || length(text) != 1) {
    return(NULL)
  }

  cleanText = trimws(text)
  if (!nzchar(cleanText)) {
    return(NULL)
  }

  paragraphs = strsplit(cleanText, "\n\\s*\n", perl = TRUE)[[1]]
  paragraphs = trimws(paragraphs)
  paragraphs = paragraphs[nzchar(paragraphs)]

  if (length(paragraphs) == 0) {
    return(NULL)
  }

  paragraphTags = lapply(paragraphs, function(paragraphText) {
    paragraphLines = strsplit(paragraphText, "\n", fixed = TRUE)[[1]]
    escapedLines = vapply(paragraphLines, function(lineText) {
      safeLine = htmlEscape(lineText, attribute = TRUE)
      gsub("'", "&#39;", safeLine, fixed = TRUE)
    }, character(1))
    tags$p(HTML(paste(escapedLines, collapse = "<br/>")))
  })

  tags$div(
    class = "wmfm-explanation-body",
    style = paste0("font-size: ", mapExplanationZoomToFontSize(zoomLevel), ";"),
    paragraphTags
  )
}

#' Build explanation provenance footer text
#'
#' @param providerLabel Character scalar provider/backend label.
#' @param modelName Character scalar model name.
#' @param generatedAt POSIXct or character time value.
#'
#' @return Character scalar provenance text.
#' @keywords internal
buildExplanationProvenanceText = function(providerLabel, modelName = NULL, generatedAt = Sys.time()) {
  providerLabel = trimws(as.character(providerLabel %||% "Unknown provider"))
  modelName = trimws(as.character(modelName %||% ""))
  timeText = format(as.POSIXct(generatedAt), "%H:%M:%S")

  providerBlock = if (nzchar(modelName)) {
    paste0(providerLabel, " (", modelName, ")")
  } else {
    providerLabel
  }

  paste0("Explanation generated by ", providerBlock, " at ", timeText)
}
